export const factionData = [
  {
    img: "/faction/0.png",
    name: "FREE NAVY",
    description1: "Cheaper upgrades, buildings and weapons. Deal more damage.",
    description2: "Lower income generation.",
    color: "#85C1E9",
    factionNumber: 0,
    attack: 1.3,
    weapon: 0.8,
    repair: 0.9,
    build: 0.9,
    upgrade: 0.75,
    transport: 1,
    scrap: 1,
    income: 1,
    sell: 1,
  },

  {
    img: "/faction/1.png",
    name: "RUSSIA",
    description1: "Lower cost for mining, transport, building & weapons",
    description2: "Lower income generation & damage.",
    color: "#A569BD",
    factionNumber: 1,
    attack: 0.8,
    weapon: 0.8,
    transport: 0.9,
    repair: 0.8,
    build: 0.9,
    scrap: 0.75,
    income: 1,
    sell: 1,
    upgrade: 1,
  },

  {
    img: "/faction/2.png",
    name: "CHINA",
    description1: "Lower costs for mining, transport, buildings & weapons.",
    description2: "Lower income generation & damage.",
    color: "#F4D03F",
    factionNumber: 2,
    attack: 0.95,
    weapon: 0.95,
    transport: 1.05,
    repair: 1.1,
    build: 1.05,
    scrap: 1.15,
    income: 1,
    sell: 0.95,
    upgrade: 1,
  },

  {
    img: "/faction/3.png",
    name: "INDIA",
    description1: "Lower costs from mining, transport, buildings & weapons",
    description2: "Lower income generation & damage",
    color: "#229954",
    factionNumber: 3,
    attack: 1.1,
    weapon: 0.95,
    transport: 0.95,
    repair: 1.15,
    build: 0.95,
    scrap: 1.05,
    income: 1.1,
    sell: 0.95,
    upgrade: 1,
  },

  {
    img: "/faction/4.png",
    name: "EU",
    description1: "Generates most income",
    description2: "Buildings & repairs cost the cost",
    color: "#566573",
    factionNumber: 4,
    repair: 0.95,
    build: 1,
    scrap: 0.95,
    income: 0.95,
    sell: 0.95,
    attack: 1,
    weapon: 1,
    transport: 1,
    upgrade: 1,
  },

  {
    img: "/faction/5.png",
    name: "USA",
    description1: "Higher income generation. Deal more damage",
    description2: "Buildings & weapons cost more",
    color: "#EC7063",
    factionNumber: 5,
    attack: 0.95,
    weapon: 0.95,
    repair: 0.95,
    build: 0.95,
    scrap: 0.95,
    income: 0.95,
    sell: 0.95,
    transport: 1,
    upgrade: 1,
  },
];
